In [1]:
import os
from cqpes.data import PIPData
from jax import numpy as jnp
from jaxpip import JaxPIPDescriptor

In [2]:
SiH4_data = PIPData.from_file(
    xyz_file=os.path.join("data", "SiH4.xyz"),
    E_file=os.path.join("data", "SiH4_CCSD-T.dat"),
)

SiH4_data.set_reference_energy()

print(repr(SiH4_data))

PIPData INFO | SiH4 (length: 84002)
PIPData INFO | E min: -291.450692 Hartree
PIPData INFO | E max: -291.228446 Hartree
PIPData INFO | V min: 0.0000 eV
PIPData INFO | V max: 6.0476 eV


In [3]:
SiH4_xyz = jnp.asarray(SiH4_data[0].xyz)
SiH4_xyz

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Array([[ 0.        ,  0.        ,  0.        ],
       [ 1.4737175 ,  0.        ,  0.        ],
       [-0.49123916,  0.6947171 , -1.2032853 ],
       [-0.49123916, -1.3894342 ,  0.        ],
       [-0.49123916,  0.6947171 ,  1.2032853 ]], dtype=float32)

In [4]:
ab4_pip = JaxPIPDescriptor.from_json(
    os.path.join("basis", "MOL_1_4_4.json"),
    alpha=1.0,
)

In [5]:
# distance vector r
r = ab4_pip.calc_r_from_xyz(SiH4_xyz)
r

Array([1.4737175, 1.4737176, 1.4737175, 1.4737176, 2.4065707, 2.4065707,
       2.4065707, 2.4065707, 2.4065707, 2.4065707], dtype=float32)

In [6]:
# morse vector m
m = ab4_pip.calc_m_from_r(r)
m

Array([0.22907233, 0.2290723 , 0.22907233, 0.2290723 , 0.09012383,
       0.09012383, 0.09012383, 0.09012383, 0.09012383, 0.09012383],      dtype=float32)

In [ ]:
# polynomial p