In [1]:
import os
from cqpes.data import PIPData
from jax import numpy as jnp
from jaxpip.descriptor import PIPDescriptor

In [2]:
# load CH4.xyz
data = PIPData.from_file("CH4.xyz")

/home/jh-li/mambaforge/envs/cqpes-env/lib/python3.9/site-packages/cqpes/data/pip_data.py:85: UserWarning: Energy file not specified, will fall back to parse the comment line in xyz file as energy.
  warnings.warn(
/home/jh-li/mambaforge/envs/cqpes-env/lib/python3.9/site-packages/cqpes/data/pip_data.py:106: UserWarning: Cannot parse energy from xyz_file comment line. Please check the xyz file or specify the energy file. Currently, the energy will be set to 0.
  warnings.warn(


In [3]:
# show xyz
xyz = jnp.array(data[0].xyz)
xyz

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Array([[ 0.88680434,  0.        ,  0.62706536],
       [-0.88680434,  0.        ,  0.62706536],
       [ 0.        ,  0.88680434, -0.62706536],
       [ 0.        , -0.88680434, -0.62706536],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32)

In [4]:
# initialize PIP descriptor

a4b_pip = PIPDescriptor.from_json(
    os.path.join("basis", "A4B_4.json")
)

a4b_pip

>>> PIPDescriptor INFO
>>> Number of atoms: 5
>>> Length of distance and Morse-like vectors: 10
>>> Length of permutation invariant polynomial: 83

In [5]:
# calculate PIP and its Jacobian matrix with respect to xyz
p, J_p_xyz = a4b_pip(xyz, with_grad=True)

In [6]:
# show p
p

Array([1.        , 1.350109  , 1.0183166 , 0.68354785, 0.68741924,
       0.08641405, 0.68741924, 0.34565625, 0.45569858, 0.17282811,
       0.15381068, 0.11601135, 0.46404523, 0.1166684 , 0.11601135,
       0.1166684 , 0.23333679, 0.05866456, 0.01955486, 0.1166684 ,
       0.01955486, 0.4614321 , 0.2320227 , 0.2320227 , 0.1166684 ,
       0.02933228, 0.1166684 , 0.11732913, 0.15381068, 0.02933228,
       0.01297882, 0.07831398, 0.03937876, 0.07831398, 0.01968938,
       0.07875752, 0.03937876, 0.03960178, 0.00248913, 0.0066003 ,
       0.03937876, 0.07875752, 0.03960178, 0.01980089, 0.01980089,
       0.00995652, 0.0066003 , 0.15574588, 0.07831398, 0.156628  ,
       0.156628  , 0.03937876, 0.07831398, 0.03937876, 0.07875752,
       0.03937876, 0.01968938, 0.01980089, 0.07875752, 0.01980089,
       0.01968938, 0.03960178, 0.03960178, 0.01991303, 0.03960178,
       0.00995652, 0.00995652, 0.03960178, 0.00995652, 0.07787295,
       0.15574588, 0.07831398, 0.07831398, 0.03937876, 0.00248

In [7]:
# show J_p(xyz)
J_p_xyz

Array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[-0.27558985,  0.        , -0.19487146],
        [ 0.27558985,  0.        , -0.19487146],
        [ 0.        , -0.27558985,  0.19487146],
        [ 0.        ,  0.27558985,  0.19487146],
        [ 0.        ,  0.        ,  0.        ]],

       [[-0.33943883,  0.        , -0.24001952],
        [ 0.33943883,  0.        , -0.24001952],
        [ 0.        , -0.33943883,  0.24001952],
        [ 0.        ,  0.33943883,  0.24001952],
        [ 0.        ,  0.        ,  0.        ]],

       ...,

       [[-0.02655071,  0.        , -0.01877419],
        [ 0.02655071,  0.        , -0.01877419],
        [ 0.        , -0.02655071,  0.01877419],
        [ 0.        ,  0.02655071,  0.01877419],
        [ 0.        ,  0.        ,  0.        ]],
