In [1]:
import os
import dpdata

import jax

# jax.config.update("jax_enable_x64", True)

from jax import numpy as jnp
from jaxpip.descriptor import PIPDescriptor

In [2]:
# load CH4.xyz
s = dpdata.System("CH4.xyz", fmt="xyz")
s

Data Summary
Unlabeled System
-------------------
Frame Numbers     : 1
Atom Numbers      : 5
Element List      :
-------------------
C  H
1  4

In [3]:
# show xyz
xyz = jnp.array(s.data["coords"][0])
xyz

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)


Array([[ 0.88680434,  0.        ,  0.62706536],
       [-0.88680434,  0.        ,  0.62706536],
       [ 0.        ,  0.88680434, -0.62706536],
       [ 0.        , -0.88680434, -0.62706536],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32)

In [4]:
a4b_pip = PIPDescriptor.from_json(
    os.path.join("basis", "A4B_4.json"),
    alpha=1.0,
    with_grad=False,
    dtype=jnp.float32,
)

a4b_pip

In [5]:
a4b_pip_with_grad = PIPDescriptor.from_json(
    os.path.join("basis", "A4B_4.json"),
    alpha=1.0,
    with_grad=True,
    dtype=jnp.float32,
)

a4b_pip_with_grad

In [6]:
p = a4b_pip(xyz)

p

Array([1.        , 1.350109  , 1.0183166 , 0.68354785, 0.6874192 ,
       0.08641404, 0.6874192 , 0.3456562 , 0.45569858, 0.17282808,
       0.1538107 , 0.11601132, 0.4640452 , 0.11666837, 0.11601131,
       0.11666837, 0.23333678, 0.05866456, 0.01955486, 0.11666837,
       0.01955486, 0.46143213, 0.23202269, 0.23202269, 0.11666837,
       0.02933228, 0.11666837, 0.11732913, 0.1538107 , 0.02933228,
       0.01297882, 0.07831397, 0.03937875, 0.07831398, 0.01968937,
       0.07875751, 0.03937875, 0.03960177, 0.00248913, 0.0066003 ,
       0.03937875, 0.07875751, 0.03960177, 0.01980089, 0.01980089,
       0.00995652, 0.0066003 , 0.15574588, 0.07831398, 0.156628  ,
       0.156628  , 0.03937875, 0.07831398, 0.03937875, 0.07875751,
       0.03937875, 0.01968937, 0.01980089, 0.07875751, 0.01980089,
       0.01968937, 0.03960177, 0.03960177, 0.01991303, 0.03960177,
       0.00995652, 0.00995652, 0.03960177, 0.00995652, 0.07787294,
       0.15574588, 0.07831398, 0.07831398, 0.03937875, 0.00248

In [7]:
%%timeit

p = a4b_pip(xyz)

14.3 µs ± 380 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
p, J_p_xyz = a4b_pip_with_grad(xyz)

In [9]:
p

Array([1.        , 1.350109  , 1.0183166 , 0.68354785, 0.6874192 ,
       0.08641404, 0.6874192 , 0.3456562 , 0.45569858, 0.17282808,
       0.1538107 , 0.11601132, 0.4640452 , 0.11666837, 0.11601131,
       0.11666837, 0.23333678, 0.05866456, 0.01955486, 0.11666837,
       0.01955486, 0.46143213, 0.23202269, 0.23202269, 0.11666837,
       0.02933228, 0.11666837, 0.11732913, 0.1538107 , 0.02933228,
       0.01297882, 0.07831397, 0.03937875, 0.07831398, 0.01968937,
       0.07875751, 0.03937875, 0.03960177, 0.00248913, 0.0066003 ,
       0.03937875, 0.07875751, 0.03960177, 0.01980089, 0.01980089,
       0.00995652, 0.0066003 , 0.15574588, 0.07831398, 0.156628  ,
       0.156628  , 0.03937875, 0.07831398, 0.03937875, 0.07875751,
       0.03937875, 0.01968937, 0.01980089, 0.07875751, 0.01980089,
       0.01968937, 0.03960177, 0.03960177, 0.01991303, 0.03960177,
       0.00995652, 0.00995652, 0.03960177, 0.00995652, 0.07787294,
       0.15574588, 0.07831398, 0.07831398, 0.03937875, 0.00248

In [10]:
J_p_xyz

Array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[-2.7558985e-01,  0.0000000e+00, -1.9487146e-01],
        [ 2.7558985e-01,  0.0000000e+00, -1.9487146e-01],
        [ 0.0000000e+00, -2.7558985e-01,  1.9487146e-01],
        [ 0.0000000e+00,  2.7558985e-01,  1.9487146e-01],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[-3.3943883e-01,  0.0000000e+00, -2.4001952e-01],
        [ 3.3943883e-01,  0.0000000e+00, -2.4001952e-01],
        [ 0.0000000e+00, -3.3943883e-01,  2.4001952e-01],
        [ 0.0000000e+00,  3.3943883e-01,  2.4001952e-01],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       ...,

       [[-2.6550706e-02,  2.3283064e-10, -1.8774187e-02],
        [ 2.6550706e-02,  0.0000000e+00, -1.8774187e-

In [ ]:
%%timeit

p, J_p_xyz = a4b_pip_with_grad(xyz)

71.3 µs ± 2.75 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


: 